### ISSUE TITLE
Question to Use export.py 

### ISSUE THREAD

**Issue by June1124** [athrunsunny/landmark-face#2]
hi, I tried exporting the tflite model to use on my NPU device, but that didn't seem to work.
The data input type is required to be uint8.

**Comment by athrunsunny** [comment]
I have noticed this problem, which is caused by models/tf.py and some other configs of this code,I will solve it as soon as possible

**Comment by June1124** [comment]
> I have noticed this problem, which is caused by models/tf.py and some other configs of this code,I will solve it as soon as possible

Thanks to your work on this, my project is up and running successfully.
