### ISSUE TITLE
Have you considered adding L, X, M to your model training?

### ISSUE THREAD

**Issue by June1124** [athrunsunny/landmark-face#3]

**Comment by athrunsunny** [comment]
M has a pretrained model in Baidu Cloud, and L and X will be added later

**Comment by June1124** [comment]
> M has a pretrained model in Baidu Cloud, and L and X will be added later
Thanks for your work. Now  I'm training yolov5m-lmk with 30 points in my project, and I got P/R/mAP =0 while training, as shown below. I think this is a bug,.
    38/299     4.46G   0.01495  0.004268         0   0.01917   0.03838         3       640: 100%|██████████| 54/54 [00:22<00:00,  2.35it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 4/4 [00:00<00:00,  4.52it/s]
                 all          47          47           0           0           0           0

**Comment by June1124** [comment]
I have located that this non_max_suppression_face function in the landmarks/general.py file is causing the problem, do you have a recommendation for a change?

**Comment by athrunsunny** [comment]
30 points?means add another 25 points?
You must modify the code,this code has no adaptive keypoints number.(preprocess,postprocess and detect head)

**Comment by June1124** [comment]
Yes, I have modified the relevant code and can train successfully. But maybe there is something wrong with the modification that causes the above problem.

**Comment by athrunsunny** [comment]
Are there bounding boxes except for keypoints?

**Comment by June1124** [comment]
Yes, my input is 1 (object ID) + 4 (bounding box) + 60 (30 points).

**Comment by June1124** [comment]
![image](https://user-images.githubusercontent.com/52447302/202126512-bc11a594-bb56-46f4-a239-1cfa4c880daa.png)

**Comment by June1124** [comment]
In my dataset, the format of the box is center_x, center_y, width, height.

**Comment by athrunsunny** [comment]
Maybe you can see ComputeLoss() or metrics.py ap_per_class()

**Comment by June1124** [comment]
Thanks, i will try it.

**Comment by June1124** [comment]
Sorry to bother you again, I have good news, the problem has been located to the run function in val.py, the if here can't get in, do you have any modification suggestions?
![微信图片_20221117104228](https://user-images.githubusercontent.com/52447302/202341750-28b283af-c2c6-4267-9c48-ad7901e757dc.png)

**Comment by athrunsunny** [comment]
You can check the predicted output value after NMS. If the output shape meets your expectations, you can check val.py process_batch()

**Comment by June1124** [comment]
I confirmed the size after NMS, (21168, 66), and this is as I expected.
I found the root of the problem due to the model inference section in val.py, the values of preds[:,66] in the output are all equal to 0. I guess this is a problem with the model.
![image](https://user-images.githubusercontent.com/52447302/202394410-5b54b49e-979a-45bf-a321-4a13bb6d81a0.png)

**Comment by athrunsunny** [comment]
cls_conf==0,There may be some problems with your detection head
